import os

os.environ["KERAS_BACKEND"] = "torch"

from utils import Dataset


config = {
    "beauty": (
        Dataset("Beauty_and_Personal_Care_2023"),
        {
            "raw_data": """pd.read_feather("_datasets/Beauty_and_Personal_Care/ratings.feather")""",
            "item_id_name": "item_id",
            "user_id_name": "user_id",
            "value_name": "rating",
            "timestamp_name": "timestamp",
            "min_value_to_keep": 4.0,
            "user_min_support": 7,
            "item_min_support": 10,
            "set_all_values_to": 1.0,
            "num_test_users": 10000,
            "random_state": 42,
            "load_previous_splits": False,
            "items_raw_data": """pd.read_feather("_datasets/Beauty_and_Personal_Care/item_text_descriptions.feather")""",
            "items_item_id_name": "item_id",
            "items_preprocess": """f'{row.description}'""",
            "coldstart_fraction": 0.1,
            "num_coldstart_items": 2000,
            "ts_part": 0.2,
        },
    ),
    "grocery": (
        Dataset("Grocery_and_Gourmet_Food_2023"),
        {
            "raw_data": """pd.read_feather("_datasets/Grocery_and_Gourmet_Food/ratings.feather")""",
            "item_id_name": "item_id",
            "user_id_name": "user_id",
            "value_name": "rating",
            "timestamp_name": "timestamp",
            "min_value_to_keep": 4.0,
            "user_min_support": 7,
            "item_min_support": 7,
            "set_all_values_to": 1.0,
            "num_test_users": 10000,
            "random_state": 42,
            "load_previous_splits": False,
            "items_raw_data": """pd.read_feather("_datasets/Grocery_and_Gourmet_Food/item_text_descriptions.feather")""",
            "items_item_id_name": "item_id",
            "items_preprocess": """f'{row.description}'""",
            "coldstart_fraction": 0.1,
            "num_coldstart_items": 2000,
            "ts_part": 0.2,
        },
    ),
    "office": (
        Dataset("Office_Products_2023"),
        {
            "raw_data": """pd.read_feather("_datasets/Office_Products/ratings.feather")""",
            "item_id_name": "item_id",
            "user_id_name": "user_id",
            "value_name": "rating",
            "timestamp_name": "timestamp",
            "min_value_to_keep": 4.0,
            "user_min_support": 5,
            "item_min_support": 5,
            "set_all_values_to": 1.0,
            "num_test_users": 10000,
            "random_state": 42,
            "load_previous_splits": False,
            "items_raw_data": """pd.read_feather("_datasets/Office_Products/item_text_descriptions.feather")""",
            "items_item_id_name": "item_id",
            "items_preprocess": """f'{row.description}'""",
            "coldstart_fraction": 0.1,
            "num_coldstart_items": 2000,
            "ts_part": 0.2,
        },
    ),
    "toys": (
        Dataset("Toys_and_Games_2023"),
        {
            "raw_data": """pd.read_feather("_datasets/Toys_and_Games/ratings.feather")""",
            "item_id_name": "item_id",
            "user_id_name": "user_id",
            "value_name": "rating",
            "timestamp_name": "timestamp",
            "min_value_to_keep": 4.0,
            "user_min_support": 6,
            "item_min_support": 9,
            "set_all_values_to": 1.0,
            "num_test_users": 10000,
            "random_state": 42,
            "load_previous_splits": False,
            "items_raw_data": """pd.read_feather("_datasets/Toys_and_Games/item_text_descriptions.feather")""",
            "items_item_id_name": "item_id",
            "items_preprocess": """f'{row.description}'""",
            "coldstart_fraction": 0.1,
            "num_coldstart_items": 2000,
            "ts_part": 0.2,
        },
    ),
    "goodbooks": (
        Dataset("Goodbooks-10k"),
        {
            "raw_data": """pd.read_csv("_datasets/goodbooks/ratings.csv")""",
            "user_id_name": "user_id",
            "item_id_name": "book_id",
            "value_name": "rating",
            "min_value_to_keep": 4.0,
            "user_min_support": 5,
            "item_min_support": 1,
            "set_all_values_to": 1.0,
            "num_test_users": 2500,
            "random_state": 42,
            "load_previous_splits": False,
            "items_raw_data": """pd.read_feather("_datasets/goodbooks/item_text_descriptions.feather")""",
            "items_item_id_name": "book_id",
            "items_preprocess": """f'{row.llama31_description}'""",
            "coldstart_fraction": 0.1,
            "num_coldstart_items": 2000,
            "ts_part": 0.2,
        },
    ),
    "hm": (
        Dataset("HM"),
        {
            "raw_data": """pd.read_feather("_datasets/HM/ratings.feather")""",
            "item_id_name": "item_id",
            "user_id_name": "user_id",
            "value_name": "rating",
            "timestamp_name": "timestamp",
            "min_value_to_keep": 1.0,
            "user_min_support": 10,
            "item_min_support": 5,
            "set_all_values_to": 1.0,
            "num_test_users": 10000,
            "random_state": 42,
            "load_previous_splits": False,
            "items_raw_data": """pd.read_feather("_datasets/HM/item_text_descriptions.feather")""",
            "items_item_id_name": "item_id",
            "items_preprocess": """f'{row.description}'""",
            "coldstart_fraction": 0.1,
            "num_coldstart_items": 2000,
            "ts_part": 0.2,
        },
    ),
}
